## module, package, library

Modules, aka (also known as) packages or libraries offer additional functions (function calls or class). 
Built-in modules (such as os, sys) are written by Python, you could import directly without additional installation.

External modules are developed by kind people of (open-source) Python community. They are shared on https://pypi.org/.
Installation is needed. For example
```
# if using anaconda
$ conda install numpy

# if using pure python interpreter
$ pip install numpy
```

In [11]:
# operating system
import os
print('This computer runs on', os.name,'operating system') # NT means Microsoft Windows O/S

# my machine (computer) name
import socket # bad practice here (import should be hoisted/put at the top of the file)
print('This computer name is', socket.gethostname())

This computer runs on nt operating system (NT means Microsoft Windows
This computer name is Vulcan


In [18]:
# python version
import sys

print('Python version:', sys.version, '(', sys.platform, ')')
print('Python version (full info):', sys.version_info)

Python version: 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)] ( win32 )
Python version (full info): sys.version_info(major=3, minor=10, micro=7, releaselevel='final', serial=0)


In [20]:
# import numpy
# numpy is an external module/package, you need to install manually, $ pip install numpy
import numpy as np # import and then alias as "np"

# type the following: np. ctrl-space
print(np.ones(4)) # observe: 1. is a float (floating-point)
print(np.zeros(4)) # "0." is a float as well
print(np.array([1,2,3,4]))
print(np.random.random(5)) # generate 5 random numbers (0-0.999....)


[1. 1. 1. 1.]
[0. 0. 0. 0.]
[1 2 3 4]
[0.75407241 0.79649187 0.99418744 0.88553591 0.35575365]


In [21]:
# import "sub-feature"
from numpy import random as rand # pseudo code: rand = (import numpy).random
print(rand.random(5)) # numpy.random.random(5)

[0.2601953  0.06306881 0.65732135 0.25266945 0.81005372]
