## Numpy is a third party library for vector & matrix manipulation

In [1]:
# to install numpy in jupyter notebook
! pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [2]:
# import numpy
# numpy is an external module/package, you need to install manually, $ pip install numpy
import numpy as np # import and then alias as "np"


In [4]:
# data generation

# type the following: np. ctrl-space
print(np.ones(4)) # observe: 1. is a float (floating-point)
print(np.zeros(4)) # "0." is a float as well
print(np.array([1,2,3,4]))
print(np.random.random(5)) # generate 5 random numbers (0-0.999....)

print(np.linspace(-1, 1, 10)) # generate 10 linearly spaced between -1 and 1

[1. 1. 1. 1.]
[0. 0. 0. 0.]
[1 2 3 4]
[0.9894602  0.62811431 0.36365392 0.78464236 0.05183141]
[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]


In [ ]:
# math convention: matrix is multi-dimensional
matrix = np.array([[1,2,3],[4,5,6]]) # two dimensional array
print("value of a matrix is: ", matrix, "\nshape of a matrix is: ", matrix.shape)

# naming convention: vector is one-dimensional
vector = np.array([5,6,7,8])
print("value of a vector is: ", vector, "\nshape of a vector is: ", vector.shape) # value the shape

# vector multiplication
vec_a = np.array([1,2,3])
vec_b = np.array([4,5,6]).transpose()
print('vector multiplication: ', vec_a @ vec_b) # 1*4 + 2*5 + 3*6

# matrix multiplication
mat_a = np.array([[1,2,3],[4,5,6]])
mat_b = np.array([[4,5],[7,8], [9,10]])
print('matrix multiplication: ', mat_a @ mat_b)


value of a matrix is:  [[1 2 3]
 [4 5 6]] 
shape of a matrix is:  (2, 3)
value of a vector is:  [5 6 7 8] 
shape of a vector is:  (4,)
vector multiplication:  32
matrix multiplication:  [[ 45  51]
 [105 120]]
